version: '3.8'

services:
  alembic:
    build:
      context: .
      dockerfile: ./app/alembic/Dockerfile
    volumes:
      - ./app/alembic:/app/alembic
      - ./wait-for-it.sh:/app/wait-for-it.sh
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=smart_bucket
    command: ["alembic", "upgrade", "head"]

  fastapi:
    build:
      context: .
      dockerfile: ./app/fast_api/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=smart_bucket

  parser:
    build:
      context: .
      dockerfile: ./app/parser/Dockerfile
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=smart_bucket
      - PYTHONPATH=/app

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smart_bucket
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
