version: "3.9"

services:
  db:
    image: postgres:17
    container_name: pgdb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  parser:
    build:
      context: .
      dockerfile: Dockerfile.parser
    depends_on:
      - db
    environment:
      DB_URL: postgresql+asyncpg://postgres:postgres@db:5432/smart

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_URL: postgresql+asyncpg://user:password@db:5432/mydatabase

volumes:
  postgres_data:
